### ISSUE TITLE
Hope to release a library version compatible with ESP32c2

### ISSUE THREAD

**Issue by odddouglas** [h2zero/NimBLE-Arduino#949]
my code:
```cpp
#include <Arduino.h>
#include <NimBLEDevice.h>

// === Global Variables ===
static NimBLEServer *pServer;
NimBLECharacteristic *pCharacteristicRX = nullptr;
NimBLECharacteristic *pCharacteristicTX = nullptr;

// === Server Callback ===
class ServerCallbacks : public NimBLEServerCallbacks
{
    void onConnect(NimBLEServer *pServer, NimBLEConnInfo &connInfo) override
    {
        Serial.printf("Client connected: %s\n", connInfo.getAddress().toString().c_str());
    }

    void onDisconnect(NimBLEServer *pServer, NimBLEConnInfo &connInfo, int reason) override
    {
        Serial.println("Client disconnected, restarting advertising");
        NimBLEDevice::startAdvertising();
    }
};

// === Characteristic Callback ===
class CharacteristicCallbacks : public NimBLECharacteristicCallbacks
{
    void onWrite(NimBLECharacteristic *pCharacteristic, NimBLEConnInfo &connInfo) override
    {
        String val = pCharacteristic->getValue();
        if (val != "")
        {
            Serial.println("Data received: " + val);
        }
    }
};

// === BLE Initialization ===
void setup()
{
    Serial.begin(115200);

    NimBLEDevice::init("BLE_Server");

    pServer = NimBLEDevice::createServer();
    pServer->setCallbacks(new ServerCallbacks());

    NimBLEService *pService = pServer->createService("ABC0");

    pCharacteristicRX = pService->createCharacteristic(
        "ABC1",
        NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::WRITE);
    pCharacteristicRX->setCallbacks(new CharacteristicCallbacks());

    pCharacteristicTX = pService->createCharacteristic(
        "ABC2",
        NIMBLE_PROPERTY::NOTIFY);

    pService->start();

    NimBLEAdvertising *pAdvertising = NimBLEDevice::getAdvertising();
    pAdvertising->addServiceUUID("ABC0");
    pAdvertising->setName("BLE_Server"); // Ensure the advertising name is correct
    pAdvertising->start();

    Serial.println("BLE service initialized, starting advertising...");
}

void loop() {
    // Main loop remains empty
}
```
error:
```bash
In file included from C:\Users\odddouglas\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.4-2f7dcd86-v1\esp32c2/include/bt/include/esp32c2/include/esp_bt.h:17,
                 from e:\ODDDOUGLAS\mini-project\project\smarthost_gateway\arduino\libraries\NimBLE-Arduino\src/NimBLEDevice.h:25,
                 from E:\ODDDOUGLAS\mini-project\project\smarthost_gateway\arduino\esp32c2\esp32c2.ino:2:
C:/Users/odddouglas/AppData/Local/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.4-2f7dcd86-v1/esp32c2/include/bt/controller/esp32c2/esp_bt_cfg.h:19:10: fatal error: syscfg/syscfg.h: No such file or directory
   19 | #include "syscfg/syscfg.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1
```

**Comment by h2zero** [comment]
Current master branch supports the C2

**Comment by Jason2866** [comment]
C2 does compile with Arduino Core 3.2.0 based on IDF 5.4.1+
Trying to compile with upcoming Core 3.3.0 based on IDF 5.5.0 i see this 
```
Compiling .pio/build/esp32c2/lib4e9/NimBLE-Arduino/nimble/nimble/host/src/ble_sm_lgcy.c.o
.pio/libdeps/esp32c2/NimBLE-Arduino/src/nimble/nimble/host/src/ble_sm_alg.c:618:22: error: 'ble_sm_alg_dbg_priv_key' defined but not used [-Werror=unused-const-variable=]
  618 | static const uint8_t ble_sm_alg_dbg_priv_key[32] = {
      |                      ^~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
```
CI from a PR to add a NimBLE example for different MCUs to pioarduino branch develop33.

There is no issue with branch develop. Here i have already added the NimBLE example.

**Comment by h2zero** [comment]
Thanks for that @Jason2866, looks like you're correct, will fix shortly.

**Comment by Jason2866** [comment]
@h2zero 
Still not working. Compiling Arduino as an component (Hybrid Compile mode from pioarduino) https://github.com/pioarduino/platform-espressif32/actions/runs/15554520393/job/43791949943
```
Generating project linker script .pio/build/esp32c2/sections.ld
Linking .pio/build/esp32c2/firmware.elf
/home/runner/.platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: .pio/build/esp32c2/esp-idf/esp_security/libesp_security.a(esp_crypto_lock.c.o): in function `esp_crypto_ecc_lock_acquire':
/home/runner/.platformio/packages/framework-espidf/components/esp_security/src/esp_crypto_lock.c:126: multiple definition of `esp_crypto_ecc_lock_acquire'; .pio/build/esp32c2/lib4e9/NimBLE-Arduino/nimble/esp_port/esp-hci/src/na_hci_driver.c.o:/home/runner/work/platform-espressif32/platform-espressif32/examples/arduino-NimBLE-ext_client/.pio/libdeps/esp32c2/NimBLE-Arduino/src/nimble/esp_port/esp-hci/src/na_hci_driver.c:88: first defined here
/home/runner/.platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: .pio/build/esp32c2/esp-idf/esp_security/libesp_security.a(esp_crypto_lock.c.o): in function `esp_crypto_ecc_lock_release':
/home/runner/.platformio/packages/framework-espidf/components/esp_security/src/esp_crypto_lock.c:131: multiple definition of `esp_crypto_ecc_lock_release'; .pio/build/esp32c2/lib4e9/NimBLE-Arduino/nimble/esp_port/esp-hci/src/na_hci_driver.c.o:/home/runner/work/platform-espressif32/platform-espressif32/examples/arduino-NimBLE-ext_client/.pio/libdeps/esp32c2/NimBLE-Arduino/src/nimble/esp_port/esp-hci/src/na_hci_driver.c:89: first defined here
collect2: error: ld returned 1 exit status
*** [.pio/build/esp32c2/firmware.elf] Error 1
```
