### ISSUE TITLE
2.3.0 compilation error: multiple definition of bt_record_hci_data

### ISSUE THREAD

**Issue by swiergot** [h2zero/NimBLE-Arduino#967]
After upgrading to 2.3.0 I'm getting the following linker error:

```
/home/build/.arduino15/packages/esp32/tools/esp-x32/2411/bin/xtensa-esp32-elf-g++ -Wl,--Map=/home/build/.cache/arduino/sketches/F6542AFFD67E94FCD539B7BB53BA387B/project.ino.map -L/home/build/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.4-2f7dcd86-v1/esp32/lib -L/home/build/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.4-2f7dcd86-v1/esp32/ld -L/home/build/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.4-2f7dcd86-v1/esp32/qio_qspi -Wl,--wrap=esp_panic_handler @/home/build/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.4-2f7dcd86-v1/esp32/flags/ld_flags @/home/build/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.4-2f7dcd86-v1/esp32/flags/ld_scripts -Wl,--start-group sketch/ArduinoNvs.cpp.o sketch/HttpsOTAUpdate.cpp.o sketch/WiFiProv.cpp.o sketch/project.ino.cpp.o sketch/esp_encrypted_img.c.o sketch/esp_https_ota.c.o libraries/NimBLE-Arduino/NimBLE2904.cpp.o libraries/NimBLE-Arduino/NimBLEAddress.cpp.o libraries/NimBLE-Arduino/NimBLEAdvertisedDevice.cpp.o libraries/NimBLE-Arduino/NimBLEAdvertisementData.cpp.o libraries/NimBLE-Arduino/NimBLEAdvertising.cpp.o libraries/NimBLE-Arduino/NimBLEAttValue.cpp.o libraries/NimBLE-Arduino/NimBLEBeacon.cpp.o libraries/NimBLE-Arduino/NimBLECharacteristic.cpp.o libraries/NimBLE-Arduino/NimBLEClient.cpp.o libraries/NimBLE-Arduino/NimBLEDescriptor.cpp.o libraries/NimBLE-Arduino/NimBLEDevice.cpp.o libraries/NimBLE-Arduino/NimBLEEddystoneTLM.cpp.o libraries/NimBLE-Arduino/NimBLEExtAdvertising.cpp.o libraries/NimBLE-Arduino/NimBLEHIDDevice.cpp.o libraries/NimBLE-Arduino/NimBLEL2CAPChannel.cpp.o libraries/NimBLE-Arduino/NimBLEL2CAPServer.cpp.o libraries/NimBLE-Arduino/NimBLERemoteCharacteristic.cpp.o libraries/NimBLE-Arduino/NimBLERemoteDescriptor.cpp.o libraries/NimBLE-Arduino/NimBLERemoteService.cpp.o libraries/NimBLE-Arduino/NimBLERemoteValueAttribute.cpp.o libraries/NimBLE-Arduino/NimBLEScan.cpp.o libraries/NimBLE-Arduino/NimBLEServer.cpp.o libraries/NimBLE-Arduino/NimBLEService.cpp.o libraries/NimBLE-Arduino/NimBLEUUID.cpp.o libraries/NimBLE-Arduino/NimBLEUtils.cpp.o libraries/NimBLE-Arduino/nimble/esp_port/esp-hci/src/esp_nimble_hci.c.o libraries/NimBLE-Arduino/nimble/esp_port/esp-hci/src/na_hci_driver.c.o libraries/NimBLE-Arduino/nimble/esp_port/esp-hci/src/na_hci_transport.c.o libraries/NimBLE-Arduino/nimble/esp_port/port/src/exp_nimble_mem.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/aes_decrypt.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/aes_encrypt.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/cbc_mode.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/ccm_mode.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/cmac_mode.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/ctr_mode.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/ctr_prng.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/ecc.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/ecc_dh.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/ecc_dsa.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/ecc_platform_specific.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/hmac.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/hmac_prng.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/sha256.c.o libraries/NimBLE-Arduino/nimble/ext/tinycrypt/src/utils.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_adv.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_conn.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_conn_hci.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_crypto.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_ctrl.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_dtm.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_hci.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_hci_ev.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_hci_supp_cmd.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_hci_vs.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_iso.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_iso_big.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_isoal.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_pdu.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_rand.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_resolv.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_rfmgmt.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_scan.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_scan_aux.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_sched.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_sync.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_trace.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_utils.c.o libraries/NimBLE-Arduino/nimble/nimble/controller/src/ble_ll_whitelist.c.o libraries/NimBLE-Arduino/nimble/nimble/drivers/nrf51/src/ble_hw.c.o libraries/NimBLE-Arduino/nimble/nimble/drivers/nrf51/src/ble_phy.c.o libraries/NimBLE-Arduino/nimble/nimble/drivers/nrf5x/src/ble_hw.c.o libraries/NimBLE-Arduino/nimble/nimble/drivers/nrf5x/src/ble_phy.c.o libraries/NimBLE-Arduino/nimble/nimble/drivers/nrf5x/src/ble_phy_trace.c.o libraries/NimBLE-Arduino/nimble/nimble/drivers/nrf5x/src/nrf52/phy.c.o libraries/NimBLE-Arduino/nimble/nimble/drivers/nrf5x/src/nrf53/phy.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/access.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/adv.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/adv_ext.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/adv_legacy.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/aes-ccm.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/app_keys.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/beacon.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/cdb.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/cfg.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/cfg_cli.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/cfg_srv.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/crypto.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/friend.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/glue.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/health_cli.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/health_srv.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/heartbeat.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/light_model.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/lpn.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/mesh.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/model_cli.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/model_srv.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/msg.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/net.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/pb_adv.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/pb_gatt.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/pb_gatt_srv.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/prov.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/prov_device.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/provisioner.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/proxy.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/proxy_msg.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/proxy_srv.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/rpl.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/settings.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/shell.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/subnet.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/testing.c.o libraries/NimBLE-Arduino/nimble/nimble/host/mesh/src/transport.c.o libraries/NimBLE-Arduino/nimble/nimble/host/services/gap/src/ble_svc_gap.c.o libraries/NimBLE-Arduino/nimble/nimble/host/services/gatt/src/ble_svc_gatt.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_aes_ccm.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_att.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_att_clt.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_att_cmd.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_att_svr.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_dtm.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_ead.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_eatt.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_eddystone.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_gap.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_gattc.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_gattc_cache.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_gattc_cache_conn.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_gatts.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_gatts_lcl.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_adv.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_atomic.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_cfg.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_conn.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_flow.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_hci.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_hci_cmd.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_hci_evt.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_hci_util.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_id.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_log.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_mbuf.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_misc.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_mqueue.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_periodic_sync.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_pvcy.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_resolv.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_shutdown.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_startup.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_hs_stop.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_ibeacon.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_l2cap.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_l2cap_coc.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_l2cap_sig.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_l2cap_sig_cmd.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_sm.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_sm_alg.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_sm_cmd.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_sm_lgcy.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_sm_sc.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_store.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_store_util.c.o libraries/NimBLE-Arduino/nimble/nimble/host/src/ble_uuid.c.o libraries/NimBLE-Arduino/nimble/nimble/host/store/config/src/ble_store_config.c.o libraries/NimBLE-Arduino/nimble/nimble/host/store/config/src/ble_store_config_conf.c.o libraries/NimBLE-Arduino/nimble/nimble/host/store/config/src/ble_store_nvs.c.o libraries/NimBLE-Arduino/nimble/nimble/host/store/ram/src/ble_store_ram.c.o libraries/NimBLE-Arduino/nimble/nimble/host/util/src/addr.c.o libraries/NimBLE-Arduino/nimble/nimble/transport/common/hci_h4/src/hci_h4.c.o libraries/NimBLE-Arduino/nimble/nimble/transport/common/hci_ipc/src/hci_ipc.c.o libraries/NimBLE-Arduino/nimble/nimble/transport/esp_ipc/src/hci_esp_ipc.c.o libraries/NimBLE-Arduino/nimble/nimble/transport/esp_ipc_legacy/src/hci_esp_ipc_legacy.c.o libraries/NimBLE-Arduino/nimble/nimble/transport/nrf5340/src/nrf5340_ble_hci.c.o libraries/NimBLE-Arduino/nimble/nimble/transport/src/transport.c.o libraries/NimBLE-Arduino/nimble/porting/nimble/src/endian.c.o libraries/NimBLE-Arduino/nimble/porting/nimble/src/hal_timer.c.o libraries/NimBLE-Arduino/nimble/porting/nimble/src/mem.c.o libraries/NimBLE-Arduino/nimble/porting/nimble/src/nimble_port.c.o libraries/NimBLE-Arduino/nimble/porting/nimble/src/os_cputime.c.o libraries/NimBLE-Arduino/nimble/porting/nimble/src/os_cputime_pwr2.c.o libraries/NimBLE-Arduino/nimble/porting/nimble/src/os_mbuf.c.o libraries/NimBLE-Arduino/nimble/porting/nimble/src/os_mempool.c.o libraries/NimBLE-Arduino/nimble/porting/nimble/src/os_msys_init.c.o libraries/NimBLE-Arduino/nimble/porting/npl/freertos/src/nimble_port_freertos.c.o libraries/NimBLE-Arduino/nimble/porting/npl/freertos/src/npl_os_freertos.c.o libraries/WiFi/AP.cpp.o libraries/WiFi/STA.cpp.o libraries/WiFi/WiFi.cpp.o libraries/WiFi/WiFiAP.cpp.o libraries/WiFi/WiFiGeneric.cpp.o libraries/WiFi/WiFiMulti.cpp.o libraries/WiFi/WiFiSTA.cpp.o libraries/WiFi/WiFiScan.cpp.o libraries/Network/NetworkClient.cpp.o libraries/Network/NetworkEvents.cpp.o libraries/Network/NetworkInterface.cpp.o libraries/Network/NetworkManager.cpp.o libraries/Network/NetworkServer.cpp.o libraries/Network/NetworkUdp.cpp.o libraries/NetworkClientSecure/NetworkClientSecure.cpp.o libraries/NetworkClientSecure/ssl_client.cpp.o libraries/PubSubClient/PubSubClient.cpp.o libraries/ESPping/ESPping.cpp.o libraries/ESPping/ping32.cpp.o libraries/SPIFFS/SPIFFS.cpp.o libraries/FS/FS.cpp.o libraries/FS/vfs_api.cpp.o libraries/SimpleBLE/SimpleBLE.cpp.o /home/build/.cache/arduino/cores/1f7bf045034b3fcd235e0936907c1b5c/core.a @/home/build/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.4-2f7dcd86-v1/esp32/flags/ld_libs -Wl,--end-group -Wl,-EL -o /home/build/.cache/arduino/sketches/F6542AFFD67E94FCD539B7BB53BA387B/project.ino.elf
/home/build/.arduino15/packages/esp32/tools/esp-x32/2411/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld: /home/build/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.4-2f7dcd86-v1/esp32/lib/libbt.a(hci_hal_h4.c.obj): in function `bt_record_hci_data':
(.text.bt_record_hci_data+0x0): multiple definition of `bt_record_hci_data'; libraries/NimBLE-Arduino/nimble/esp_port/esp-hci/src/esp_nimble_hci.c.o:/home/build/Arduino/libraries/NimBLE-Arduino/src/nimble/esp_port/esp-hci/src/esp_nimble_hci.c:203: first defined here
collect2: error: ld returned 1 exit status
```

Reverting to 2.2.3 allows successful compilation egain.

**Comment by h2zero** [comment]
Seems to be caused by the new arduino core?
