### ISSUE TITLE
2.3.2 build failure of an example sketch with recent Core 3.3.0-RC1 for C6 or C5 targets

### ISSUE THREAD

**Issue by lyusupov** [h2zero/NimBLE-Arduino#1000]
Library: 2.3.2
Core: 3.3.0-RC1

Build gives failure caused by numerous duplicated symbols :

```
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-cf8dad07-v1/esp32c6/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_encrypt':
(.text.ble_sm_alg_encrypt+0x0): multiple definition of `ble_sm_alg_encrypt'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.2/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.2/src/nimble/nimble/host/src/ble_sm_alg.c:96: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-cf8dad07-v1/esp32c6/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_s1':
(.text.ble_sm_alg_s1+0x0): multiple definition of `ble_sm_alg_s1'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.2/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.2/src/nimble/nimble/host/src/ble_sm_alg.c:140: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-cf8dad07-v1/esp32c6/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_c1':
(.text.ble_sm_alg_c1+0x0): multiple definition of `ble_sm_alg_c1'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.2/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.2/src/nimble/nimble/host/src/ble_sm_alg.c:179: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-cf8dad07-v1/esp32c6/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_aes_cmac':
(.text.ble_sm_alg_aes_cmac+0x0): multiple definition of `ble_sm_alg_aes_cmac'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.2/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.2/src/nimble/nimble/host/src/ble_sm_alg.c:256: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-cf8dad07-v1/esp32c6/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_f4':
(.text.ble_sm_alg_f4+0x0): multiple definition of `ble_sm_alg_f4'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.2/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.2/src/nimble/nimble/host/src/ble_sm_alg.c:327: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-cf8dad07-v1/esp32c6/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_f5':
(.text.ble_sm_alg_f5+0x0): multiple definition of `ble_sm_alg_f5'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.2/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.2/src/nimble/nimble/host/src/ble_sm_alg.c:373: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-cf8dad07-v1/esp32c6/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_f6':
(.text.ble_sm_alg_f6+0x0): multiple definition of `ble_sm_alg_f6'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.2/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.2/src/nimble/nimble/host/src/ble_sm_alg.c:442: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-cf8dad07-v1/esp32c6/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_g2':
(.text.ble_sm_alg_g2+0x0): multiple definition of `ble_sm_alg_g2'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.2/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.2/src/nimble/nimble/host/src/ble_sm_alg.c:488: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-cf8dad07-v1/esp32c6/lib/libbt.a(ble_sm_alg.c.obj): in function `mbedtls_free_keypair':
(.text.mbedtls_free_keypair+0x0): multiple definition of `mbedtls_free_keypair'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.2/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.2/src/nimble/nimble/host/src/ble_sm_alg.c:693: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-cf8dad07-v1/esp32c6/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_ecc_init':
(.text.ble_sm_alg_ecc_init+0x0): multiple definition of `ble_sm_alg_ecc_init'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.2/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.2/src/nimble/nimble/host/src/ble_sm_alg.c:774: first defined here
collect2: error: ld returned 1 exit status
```

To reproduce

```
arduino-cli core update-index
arduino-cli core install esp32:esp32@3.3.0-RC1
export BOARD=esp32:esp32:esp32c6
arduino-cli compile -v --build-path=/tmp/arduino -b "$BOARD" NimBLE-Arduino-2.3.2/examples/NimBLE_Client/NimBLE_Client.ino
```

Build for C5 gives the failure as well.
However, build for C3 is fine.

The failure is noticed with most recent 3.3.0-RC1
Build with previous [3.3.0-alpha1](https://github.com/espressif/arduino-esp32/tree/3.3.0-alpha1) is successful.

**Comment by h2zero** [comment]
Looks like they have enabled the nimble stack by default now so this repo will no longer work with the new cores, sad day 😞.

Using esp-nimble-cpp may be an option, sadly though you will no longer be able to configure the build settings.

**Comment by raichea** [comment]
Ugh, I've just run into this problem on a C6 while trying to get an example running on it. What a shame!

**Comment by h2zero** [comment]
I'm in the process of fixing this, will be updated shortly

**Comment by raichea** [comment]
That's great! In the meantime, I've switched back to core 3.2.1 and that avoids the problem for now.

**Comment by lyusupov** [comment]
@h2zero 
there is something wrong with [Release 2.3.3](https://github.com/h2zero/NimBLE-Arduino/releases/tag/2.3.3) and [tag 2.3.3](https://github.com/h2zero/NimBLE-Arduino/tree/2.3.3)

Build with  [Release 2.3.3](https://github.com/h2zero/NimBLE-Arduino/releases/tag/2.3.3) gives failure:

```
arduino-cli compile -v --build-path=/tmp/arduino -b "$BOARD" NimBLE-Arduino-2.3.3/examples/NimBLE_Client/NimBLE_Client.ino


/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c5/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_encrypt':
(.text.ble_sm_alg_encrypt+0x0): multiple definition of `ble_sm_alg_encrypt'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.3/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.3/src/nimble/nimble/host/src/ble_sm_alg.c:96: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c5/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_s1':
(.text.ble_sm_alg_s1+0x0): multiple definition of `ble_sm_alg_s1'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.3/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.3/src/nimble/nimble/host/src/ble_sm_alg.c:140: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c5/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_c1':
(.text.ble_sm_alg_c1+0x0): multiple definition of `ble_sm_alg_c1'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.3/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.3/src/nimble/nimble/host/src/ble_sm_alg.c:179: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c5/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_aes_cmac':
(.text.ble_sm_alg_aes_cmac+0x0): multiple definition of `ble_sm_alg_aes_cmac'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.3/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.3/src/nimble/nimble/host/src/ble_sm_alg.c:256: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c5/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_f4':
(.text.ble_sm_alg_f4+0x0): multiple definition of `ble_sm_alg_f4'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.3/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.3/src/nimble/nimble/host/src/ble_sm_alg.c:327: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c5/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_f5':
(.text.ble_sm_alg_f5+0x0): multiple definition of `ble_sm_alg_f5'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.3/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.3/src/nimble/nimble/host/src/ble_sm_alg.c:373: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c5/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_f6':
(.text.ble_sm_alg_f6+0x0): multiple definition of `ble_sm_alg_f6'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.3/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.3/src/nimble/nimble/host/src/ble_sm_alg.c:442: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c5/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_g2':
(.text.ble_sm_alg_g2+0x0): multiple definition of `ble_sm_alg_g2'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.3/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.3/src/nimble/nimble/host/src/ble_sm_alg.c:488: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c5/lib/libbt.a(ble_sm_alg.c.obj): in function `mbedtls_free_keypair':
(.text.mbedtls_free_keypair+0x0): multiple definition of `mbedtls_free_keypair'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.3/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.3/src/nimble/nimble/host/src/ble_sm_alg.c:693: first defined here
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: /home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.5-b66b5448-v1/esp32c5/lib/libbt.a(ble_sm_alg.c.obj): in function `ble_sm_alg_ecc_init':
(.text.ble_sm_alg_ecc_init+0x0): multiple definition of `ble_sm_alg_ecc_init'; /tmp/arduino/libraries/NimBLE-Arduino-2.3.3/nimble/nimble/host/src/ble_sm_alg.c.o:/home/codespace/Arduino/libraries/NimBLE-Arduino-2.3.3/src/nimble/nimble/host/src/ble_sm_alg.c:774: first defined here
collect2: error: ld returned 1 exit status
Multiple libraries were found for "NimBLEDevice.h"
  Used: /workspaces/codespaces-blank/C6/SoftRF/software/firmware/source/libraries/NimBLE-Arduino-2.3.3
  Not used: /workspaces/codespaces-blank/C6/SoftRF/software/firmware/source/libraries/NimBLE-Arduino-master
Using library NimBLE-Arduino at version 2.3.2 in folder: /workspaces/codespaces-blank/C6/SoftRF/software/firmware/source/libraries/NimBLE-Arduino-2.3.3

Used library   Version Path
NimBLE-Arduino 2.3.2   /workspaces/codespaces-blank/C6/SoftRF/software/firmware/source/libraries/NimBLE-Arduino-2.3.3

Used platform Version Path
esp32:esp32   3.3.0   /home/codespace/.arduino15/packages/esp32/hardware/esp32/3.3.0
Error during build: exit status 1
```

However, a build with 'master' branch is successful

```
arduino-cli compile -v --build-path=/tmp/arduino -b "$BOARD" NimBLE-Arduino-master/examples/NimBLE_Client/NimBLE_Client.ino

/home/codespace/.arduino15/packages/esp32/tools/esptool_py/5.0.0/esptool --chip esp32c5 elf2image --flash_mode dio --flash_freq 80m --flash_size MB --elf-sha256-offset 0xb0 -o /tmp/arduino/NimBLE_Client.ino.bin /tmp/arduino/NimBLE_Client.ino.elf
esptool.py v4.8.1
Creating esp32c5 image...
Merged 2 ELF sections
Successfully created esp32c5 image.
python3 /home/codespace/.arduino15/packages/esp32/hardware/esp32/3.3.0/tools/gen_esp32part.py -q /tmp/arduino/partitions.csv /tmp/arduino/NimBLE_lient.ino.partitions.bin
/usr/bin/env bash -c "[ ! -d \"/tmp/arduino\"/libraries/Insights ] || python3 \"/home/codespace/.arduino15/packages/esp32/hardware/esp32/3.3.0\"/ools/gen_insights_package.py /tmp/arduino NimBLE_Client.ino \"/workspaces/codespaces-blank/C6/SoftRF/software/firmware/source/libraries/NimBLE-Aruino-master/examples/NimBLE_Client\""
/usr/bin/env bash -c "[ ! -d \"/tmp/arduino\"/libraries/ESP_SR ] || [ ! -f \"/home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/if-release_v5.5-b66b5448-v1/esp32c5\"/esp_sr/srmodels.bin ] || cp -f \"/home/codespace/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-relese_v5.5-b66b5448-v1/esp32c5\"/esp_sr/srmodels.bin \"/tmp/arduino\"/srmodels.bin"
/home/codespace/.arduino15/packages/esp32/tools/esptool_py/5.0.0/esptool --chip esp32c5 merge_bin -o /tmp/arduino/NimBLE_Client.ino.merged.bin --lash_mode keep --flash_freq keep --flash_size keep 0x2000 /tmp/arduino/NimBLE_Client.ino.bootloader.bin 0x8000 /tmp/arduino/NimBLE_Client.ino.paritions.bin 0xe000 /home/codespace/.arduino15/packages/esp32/hardware/esp32/3.3.0/tools/partitions/boot_app0.bin 0x10000 /tmp/arduino/NimBLE_Clien.ino.bin
esptool.py v4.8.1
Wrote 0xd47e0 bytes to file /tmp/arduino/NimBLE_Client.ino.merged.bin, ready to flash to offset 0x0

Using library NimBLE-Arduino at version 2.3.3 in folder: /workspaces/codespaces-blank/C6/SoftRF/software/firmware/source/libraries/NimBLE-Arduinomaster
/home/codespace/.arduino15/packages/esp32/tools/esp-rv32/2411/bin/riscv32-esp-elf-size -A /tmp/arduino/NimBLE_Client.ino.elf
Sketch uses 804727 bytes (39%) of program storage space. Maximum is 2031616 bytes.
Global variables use 26288 bytes (8%) of dynamic memory, leaving 301392 bytes for local variables. Maximum is 327680 bytes.

Used library   Version Path
NimBLE-Arduino 2.3.3   /workspaces/codespaces-blank/C6/SoftRF/software/firmware/source/libraries/NimBLE-Arduino-master

Used platform Version Path
esp32:esp32   3.3.0   /home/codespace/.arduino15/packages/esp32/hardware/esp32/3.3.0
```

**Comment by h2zero** [comment]
Oops, thats what I get for rushing it I guess. I'll sort it out today.

**Comment by lyusupov** [comment]
> I'll sort it out today.

Tag 2.3.3 still points on Release 2.3.2

<img width="1328" height="569" alt="Image" src="https://github.com/user-attachments/assets/5851e732-c92c-4b96-99c0-0a5bf2d08558" />
